# SPDX-License-Identifier: MPL-2.0

version: "3.11"

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bash", "-lc", "scripts/dev --non-interactive"]
    environment:
      - STREAMLIT_SERVER_PORT=8501
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace
    working_dir: /workspace
