#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_utils.sh
source "${SCRIPT_DIR}/_utils.sh"

activate_venv

mkdir -p sbom
cyclonedx-bom -r -f json -o sbom/cyclonedx.json
