# SPDX-License-Identifier: MPL-2.0

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    name: Quality Gate
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_CACHE_DIR: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Run quality checks
        run: scripts/check

      - name: Generate SBOM
        run: scripts/sbom

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.os }}
          path: coverage.xml
          if-no-files-found: ignore

      - name: Upload SBOM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.os }}
          path: sbom/cyclonedx.json
          if-no-files-found: ignore
  license_compliance:
    name: License Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install license tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install scancode-toolkit reuse

      - name: Run ScanCode license scan
        run: scancode --license --copyright --json-pp scancode-results.json .

      - name: Upload ScanCode report
        uses: actions/upload-artifact@v4
        with:
          name: scancode-report
          path: scancode-results.json
          if-no-files-found: error

      - name: Verify SPDX headers with REUSE
        run: reuse lint
