# SPDX-License-Identifier: MPL-2.0

name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Run semantic-release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: scripts/release
